# fly.toml app configuration file generated for immersive-dash-4 on 2023-09-07T06:13:57+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "immersive-dash-4"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
  DBUSER='freedb_teguh'
  DBPASS='md#q4E$zNX4M6my'
  DBHOST='sql.freedb.tech'
  DBPORT='3306'
  DBNAME='freedb_immersive-dash-4'
  JWTSECRET='sup3rs3cr3t'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
